[package]
name = "gingerale"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_asset = "0.15.3"
# bevy_atmosphere = "0.12.2"
bevy_egui = "0.33.0"
bevy_skybox = "0.6.0"
noise = "0.9.0"
rand = "0.9.0"
